compile: main.cpp src/*.cpp src/WorldElements/*.cpp
	mpic++ -O0 -g -Wall main.cpp src/*.cpp src/WorldElements/*.cpp -o super_mario_mpi


# compile: dna_sequence_mpi.cpp
# 	mpic++ dna_sequence_mpi.cpp -o dna_sequence_mpi